spring.application.name=vivaeventos-orders
app.version=0.1.0
app.api.version=v1

server.port=8083

spring.datasource.url=jdbc:postgresql://postgres:5432/vivaeventos_orders
spring.datasource.username=devdb
spring.datasource.password=a1b2c3d4

spring.jpa.hibernate.ddl-auto=none

jwt.secret=${JWT_SECRET:dGhpc0lzQVZlcnlTZWNyZXRLZXlGb3JWYWlhRXZlbnRvc1RoYXROZWVkczUw}

services.tickets.url=${SERVICES_TICKETS_URL:http://tickets:8085}

management.server.port=8084
